sudo: false

cache:
  directories:
    - $HOME/.stack/

before_install:
  - mkdir -p ~/.local/bin
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - export PATH=~/.local/bin:$PATH
  - stack --version
  - stack setup

install:
 - stack install --only-dependencies --no-terminal

script:
 - stack test
 - stack install
 - haslex-guard src

addons:
  apt:
    packages:
    - libgmp-dev
